import os
import sys
import pandas as pd
import numpy as np
from sqlalchemy import func
from datetime import datetime

# Import the new PostgreSQL framework components
from modules.configuration.config import (
    BASE_DIR,
    DB_LOADSHEET,
    REVISION_CONTROL_DB_PATH,
)
from modules.configuration.config_env import DatabaseConfig
from modules.configuration.log_config import (
    debug_id,
    info_id,
    warning_id,
    error_id,
    set_request_id,
    get_request_id,
    log_timed_operation,
)
from modules.emtacdb.emtacdb_fts import (
    Base,
    Campus,
    Building,
    SiteLocation,
    Area,
    EquipmentGroup,
    Model,
    AssetNumber,
    Location,
    Subassembly,
    ComponentAssembly,
    AssemblyView,
)
from modules.emtacdb.emtac_revision_control_db import (
    VersionInfo,
    revision_control_engine,
    RevisionControlSession,
    AreaSnapshot,
    EquipmentGroupSnapshot,
    ModelSnapshot,
    AssetNumberSnapshot,
    LocationSnapshot,
)
from modules.emtacdb.utlity.revision_database.snapshot_utils import (
    create_snapshot,
)
from modules.initial_setup.initializer_logger import (
    initializer_logger,
    close_initializer_logger,
)


class PostgreSQLEquipmentRelationshipsLoader:
    """
    PostgreSQL-enhanced equipment relationships loader with ID-based relationship mapping.

    ✔ ARCHITECTURE:
    - Excel IDs are temporary foreign keys (NOT database primary keys)
    - Database PKs are auto-generated by PostgreSQL
    - Loader maintains internal excel_id_map for relationship resolution
    - Deduplication is based on names (natural keys), not Excel IDs

    Expected Excel workbook: Position_Loadsheet_Template.xlsx

    Sheet names (MUST match SQLAlchemy __tablename__):
        campus, building, site_location, area, equipment_group, model,
        asset_number, location, subassembly, component_assembly, assembly_view
    """

    def __init__(self):
        self.request_id = set_request_id()
        self.db_config = DatabaseConfig()
        info_id(
            "Initialized PostgreSQL Equipment Relationships Loader with ID mapping",
            self.request_id,
        )

        # ✔ CRITICAL: Excel ID → Database Object mapping
        # This is the internal mapping that resolves relationships
        self.excel_id_map = {
            "campus": {},  # {excel_id: db_campus_obj}
            "building": {},  # {excel_id: db_building_obj}
            "site_location": {},  # {excel_id: db_site_location_obj}
            "area": {},  # {excel_id: db_area_obj}
            "equipment_group": {},  # {excel_id: db_equipment_group_obj}
            "model": {},  # {excel_id: db_model_obj}
            "asset_number": {},  # {excel_id: db_asset_number_obj}
            "location": {},  # {excel_id: db_location_obj}
            "subassembly": {},  # {excel_id: db_subassembly_obj}
            "component_assembly": {},  # {excel_id: db_component_assembly_obj}
            "assembly_view": {},  # {excel_id: db_assembly_view_obj}
        }

        # Statistics tracking (per-entity)
        self.stats = {
            "campuses_processed": 0,
            "buildings_processed": 0,
            "site_locations_processed": 0,
            "areas_processed": 0,
            "equipment_groups_processed": 0,
            "models_processed": 0,
            "asset_numbers_processed": 0,
            "locations_processed": 0,
            "subassemblies_processed": 0,
            "component_assemblies_processed": 0,
            "assembly_views_processed": 0,
            "duplicates_removed": 0,
            "snapshots_created": 0,
            "errors_encountered": 0,
        }

        # Mapping from sheet/tab names → stats key
        self.stat_key_map = {
            "campus": "campuses_processed",
            "building": "buildings_processed",
            "site_location": "site_locations_processed",
            "area": "areas_processed",
            "equipment_group": "equipment_groups_processed",
            "model": "models_processed",
            "asset_number": "asset_numbers_processed",
            "location": "locations_processed",
            "subassembly": "subassemblies_processed",
            "component_assembly": "component_assemblies_processed",
            "assembly_view": "assembly_views_processed",
        }

        # Table processing order (important for foreign key relationships)
        # sheet_name, model_class, required_columns
        self.table_order = [
            (
                "campus",
                Campus,
                ["id", "name", "description", "city", "state", "country"],
            ),
            (
                "building",
                Building,
                ["id", "name", "description", "address", "campus_id"],
            ),
            (
                "site_location",
                SiteLocation,
                ["id", "title", "room_number", "site_area", "building_id"],
            ),
            (
                "area",
                Area,
                ["id", "name", "description"],
            ),
            (
                "equipment_group",
                EquipmentGroup,
                ["id", "name", "area_id", "description"],
            ),
            (
                "model",
                Model,
                ["id", "name", "description", "equipment_group_id"],
            ),
            (
                "asset_number",
                AssetNumber,
                ["id", "number", "description", "model_id"],
            ),
            (
                "location",
                Location,
                ["id", "name", "model_id", "asset_number_id", "description"],
            ),
            (
                "subassembly",
                Subassembly,
                ["id", "name", "location_id", "asset_number_id", "description"],
            ),
            (
                "component_assembly",
                ComponentAssembly,
                ["id", "name", "description", "subassembly_id", "asset_number_id"],
            ),
            (
                "assembly_view",
                AssemblyView,
                [
                    "id",
                    "name",
                    "description",
                    "component_assembly_id",
                    "asset_number_id",
                ],
            ),
        ]

    # ------------------------------------------------------------------
    #  Helper: Resolve Excel FK to Database FK
    # ------------------------------------------------------------------
    def resolve_foreign_key(self, sheet_name, excel_id):
        """
        ✔ CRITICAL: Resolve Excel ID to database primary key.

        Args:
            sheet_name: The sheet/table name (e.g., "equipment_group")
            excel_id: The Excel ID from the foreign key column

        Returns:
            Database primary key (int) or None if not found
        """
        if excel_id is None:
            return None

        try:
            excel_id = int(excel_id)
        except (ValueError, TypeError):
            warning_id(
                f"Invalid Excel ID '{excel_id}' for {sheet_name}",
                self.request_id,
            )
            return None

        db_obj = self.excel_id_map.get(sheet_name, {}).get(excel_id)

        if db_obj is None:
            warning_id(
                f"Excel ID {excel_id} not found in {sheet_name} mapping",
                self.request_id,
            )
            return None

        # Return the actual database primary key
        return db_obj.id

    # ------------------------------------------------------------------
    #  DB setup
    # ------------------------------------------------------------------
    def create_database_tables(self, session):
        """Create database tables if they don't exist."""
        try:
            info_id(
                "Creating database tables if they don't exist", self.request_id
            )
            info_id("Creating database tables...")

            engine = session.bind
            Base.metadata.create_all(engine)

            info_id("Database tables created/verified")
            info_id("Database tables created successfully", self.request_id)

        except Exception as e:
            error_id(f"Error creating database tables: {str(e)}", self.request_id)
            raise

    # ------------------------------------------------------------------
    #  Excel validation / cleaning
    # ------------------------------------------------------------------
    def validate_excel_file(self, file_path):
        """Validate the Excel file structure and required sheets."""
        info_id(f"Validating Excel file: {file_path}", self.request_id)

        if not os.path.exists(file_path):
            error_id(f"Excel file not found: {file_path}", self.request_id)
            return False, "File does not exist"

        try:
            excel_file = pd.ExcelFile(file_path)

            required_sheets = [name for name, _, _ in self.table_order]
            missing_sheets = [
                sheet for sheet in required_sheets if sheet not in excel_file.sheet_names
            ]
            if missing_sheets:
                error_id(
                    f"Missing required sheets: {missing_sheets}", self.request_id
                )
                return False, f"Missing required sheets: {missing_sheets}"

            # Validate each sheet has at least headers
            for sheet_name in required_sheets:
                df = pd.read_excel(file_path, sheet_name=sheet_name)
                if df.empty:
                    warning_id(f"Sheet '{sheet_name}' is empty", self.request_id)

            info_id("Excel file validation successful", self.request_id)
            return True, "Valid"

        except Exception as e:
            error_id(f"Error validating Excel file: {str(e)}", self.request_id)
            return False, f"Error reading file: {str(e)}"

    def clean_dataframe(self, df, required_columns, sheet_name):
        """
        Clean and validate DataFrame with enhanced error handling.

        - Drops fully empty columns.
        - Ensures all required columns exist (but treats most as optional).
        - Returns only those columns in the expected order.
        - Drops rows where the primary "identity" column is empty (name / number / title).
        """
        info_id(f"Cleaning DataFrame for sheet: {sheet_name}", self.request_id)

        try:
            original_rows = len(df)

            # Remove completely empty columns
            df = df.dropna(axis=1, how="all")

            # Remove columns that are just empty strings
            for col in list(df.columns):
                if df[col].astype(str).str.strip().eq("").all():
                    df = df.drop(columns=[col])

            # Check if all required columns exist
            missing_columns = [col for col in required_columns if col not in df.columns]

            if missing_columns:
                # Critical columns that we absolutely need
                critical_columns = {"name", "number", "title"}
                critical_missing = [c for c in missing_columns if c in critical_columns]
                optional_missing = [c for c in missing_columns if c not in critical_columns]

                if critical_missing:
                    # ✔ IMPORTANT: Check if entire sheet is empty (no data rows)
                    # If sheet has no data, don't fail - just return empty dataframe
                    if len(df) == 0 or df.dropna(how='all').empty:
                        warning_id(
                            f"Sheet {sheet_name} is empty or has no data - skipping",
                            self.request_id,
                        )
                        # Return empty dataframe with required columns
                        return pd.DataFrame(columns=required_columns)

                    # Sheet has data but missing critical columns - this is an error
                    error_id(
                        f"Missing critical columns in {sheet_name}: {critical_missing}",
                        self.request_id,
                    )
                    raise ValueError(
                        f"Missing critical columns in {sheet_name}: {critical_missing}"
                    )

                # Non-critical columns → add them as None
                if optional_missing:
                    warning_id(
                        f"Missing optional columns in {sheet_name}: {optional_missing} "
                        f"- filling with None",
                        self.request_id,
                    )
                    for col in optional_missing:
                        df[col] = None

            # Replace NaN values with None for database compatibility
            df = df.replace({np.nan: None})

            # Return only required columns in the correct order
            cleaned_df = df[required_columns].copy()

            # Decide identity column for filtering out blank rows
            if "name" in required_columns:
                critical_fields = ["name"]
            elif "number" in required_columns:
                critical_fields = ["number"]
            elif "title" in required_columns:
                critical_fields = ["title"]
            else:
                critical_fields = []

            for field in critical_fields:
                initial_count = len(cleaned_df)
                cleaned_df = cleaned_df[
                    cleaned_df[field].notna()
                    & (cleaned_df[field].astype(str).str.strip() != "")
                    ]
                removed_count = initial_count - len(cleaned_df)
                if removed_count > 0:
                    warning_id(
                        f"Removed {removed_count} rows with empty {field} in {sheet_name}",
                        self.request_id,
                    )

            final_rows = len(cleaned_df)
            info_id(
                f"Cleaned {sheet_name}: {original_rows} -> {final_rows} rows",
                self.request_id,
            )

            return cleaned_df

        except Exception as e:
            error_id(
                f"Error cleaning DataFrame for {sheet_name}: {str(e)}",
                self.request_id,
            )
            raise

    # ------------------------------------------------------------------
    #  Existing data / backup / duplicates
    # ------------------------------------------------------------------
    def check_existing_data(self, session):
        """Check for existing data in tables to prevent duplicates."""
        try:
            info_id("Checking existing data in database", self.request_id)

            existing_data = {}
            total_records = 0

            for sheet_name, model_class, _ in self.table_order:
                try:
                    count = session.query(model_class).count()
                    existing_data[sheet_name] = count
                    total_records += count
                except Exception as e:
                    warning_id(
                        f"Table {sheet_name} might not exist: {str(e)}",
                        self.request_id,
                    )
                    existing_data[sheet_name] = 0

            if total_records > 0:
                warning_id("EXISTING EQUIPMENT DATA DETECTED")
                warning_id("=" * 45)
                for sheet_name, count in existing_data.items():
                    if count > 0:
                        info_id(f"{sheet_name}: {count} records")
                info_id(f"Total Records: {total_records}")
                warning_id("Loading new data may create duplicates!")
                info_id("The system will handle duplicates automatically")

                proceed = (
                    input(
                        "Continue with equipment relationships import? (y/n): "
                    )
                    .strip()
                    .lower()
                )
                if proceed not in ["y", "yes"]:
                    info_id(
                        "User chose to skip import due to existing data",
                        self.request_id,
                    )
                    return False

            return True

        except Exception as e:
            error_id(f"Error checking existing data: {str(e)}", self.request_id)
            raise

    def create_database_backup(self, session):
        """Create a comprehensive database backup before making changes."""
        try:
            info_id("Creating database backup", self.request_id)
            info_id("Creating database backup...")

            with log_timed_operation(
                    "create_database_backup", self.request_id
            ):
                backup_directory = os.path.join(
                    BASE_DIR, "Database", "DB_LOADSHEETS_BACKUP"
                )
                os.makedirs(backup_directory, exist_ok=True)

                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                excel_file_name = f"equipment_relationships_backup_{timestamp}.xlsx"
                excel_file_path = os.path.join(
                    backup_directory, excel_file_name
                )

                backup_data = {}

                for sheet_name, model_class, columns in self.table_order:
                    try:
                        # Build data rows based on model_class
                        if model_class is Campus:
                            data = [
                                (
                                    c.id,
                                    c.name,
                                    c.description,
                                    c.city,
                                    c.state,
                                    c.country,
                                )
                                for c in session.query(Campus).all()
                            ]

                        elif model_class is Building:
                            data = [
                                (
                                    b.id,
                                    b.name,
                                    b.description,
                                    b.address,
                                    b.campus_id,
                                )
                                for b in session.query(Building).all()
                            ]

                        elif model_class is SiteLocation:
                            data = [
                                (
                                    s.id,
                                    s.title,
                                    s.room_number,
                                    s.site_area,
                                    getattr(s, "building_id", None),
                                )
                                for s in session.query(SiteLocation).all()
                            ]

                        elif model_class is Area:
                            data = [
                                (a.id, a.name, a.description)
                                for a in session.query(Area).all()
                            ]

                        elif model_class is EquipmentGroup:
                            data = [
                                (
                                    eg.id,
                                    eg.name,
                                    eg.area_id,
                                    eg.description,
                                )
                                for eg in session.query(EquipmentGroup).all()
                            ]

                        elif model_class is Model:
                            data = [
                                (
                                    m.id,
                                    m.name,
                                    m.description,
                                    m.equipment_group_id,
                                )
                                for m in session.query(Model).all()
                            ]

                        elif model_class is AssetNumber:
                            data = [
                                (
                                    an.id,
                                    an.number,
                                    an.description,
                                    an.model_id,
                                )
                                for an in session.query(AssetNumber).all()
                            ]

                        elif model_class is Location:
                            data = [
                                (
                                    loc.id,
                                    loc.name,
                                    loc.model_id,
                                    getattr(loc, "asset_number_id", None),
                                    getattr(loc, "description", None),
                                )
                                for loc in session.query(Location).all()
                            ]

                        elif model_class is Subassembly:
                            data = [
                                (
                                    sa.id,
                                    sa.name,
                                    getattr(sa, "location_id", None),
                                    getattr(sa, "asset_number_id", None),
                                    sa.description,
                                )
                                for sa in session.query(Subassembly).all()
                            ]

                        elif model_class is ComponentAssembly:
                            data = [
                                (
                                    ca.id,
                                    ca.name,
                                    ca.description,
                                    getattr(ca, "subassembly_id", None),
                                    getattr(ca, "asset_number_id", None),
                                )
                                for ca in session.query(
                                    ComponentAssembly
                                ).all()
                            ]

                        elif model_class is AssemblyView:
                            data = [
                                (
                                    av.id,
                                    av.name,
                                    av.description,
                                    getattr(
                                        av, "component_assembly_id", None
                                    ),
                                    getattr(av, "asset_number_id", None),
                                )
                                for av in session.query(AssemblyView).all()
                            ]

                        else:
                            data = []

                        backup_data[sheet_name] = pd.DataFrame(
                            data, columns=columns
                        )

                    except Exception as e:
                        warning_id(
                            f"Error backing up {sheet_name}: {str(e)}",
                            self.request_id,
                        )
                        backup_data[sheet_name] = pd.DataFrame(
                            columns=columns
                        )

                with pd.ExcelWriter(
                        excel_file_path, engine="openpyxl"
                ) as writer:
                    for sheet_name, df in backup_data.items():
                        df.to_excel(
                            writer, sheet_name=sheet_name, index=False
                        )

                info_id(
                    f"Database backup created: {excel_file_name}",
                    self.request_id,
                )
                info_id(f"Backup saved: {excel_file_name}")

        except Exception as e:
            error_id(
                f"Error creating database backup: {str(e)}", self.request_id
            )
            warning_id(f"Backup failed: {str(e)}")

    # ------------------------------------------------------------------
    #  FK-aware duplicate cleaners
    # ------------------------------------------------------------------
    def _dedupe_asset_numbers(self, session):
        """
        Merge duplicate AssetNumber rows that share the same 'number'.

        Strategy:
        - Treat AssetNumber.number as the natural key.
        - For each number with multiple rows:
            - Keep the lowest id row as canonical.
            - Re-point all FK references to the canonical id.
            - Delete the extra AssetNumber rows.
        This avoids setting any FK to NULL and keeps PostgreSQL happy.
        """
        label = "AssetNumber"
        info_id(
            f"FK-aware dedupe for {label} based on 'number'",
            self.request_id,
        )

        try:
            with session.no_autoflush:
                # Find all numbers that appear more than once
                duplicates = (
                    session.query(
                        AssetNumber.number,
                        func.count(AssetNumber.id).label("count"),
                    )
                    .group_by(AssetNumber.number)
                    .having(func.count(AssetNumber.id) > 1)
                    .all()
                )

                if not duplicates:
                    return

                duplicates_removed = 0

                for number_value, _ in duplicates:
                    rows = (
                        session.query(AssetNumber)
                        .filter(AssetNumber.number == number_value)
                        .order_by(AssetNumber.id.asc())
                        .all()
                    )

                    if len(rows) < 2:
                        continue

                    primary = rows[0]
                    extras = rows[1:]

                    debug_id(
                        f"[AssetNumber dedupe] number={number_value}, "
                        f"keeping id={primary.id}, merging {len(extras)} duplicates",
                        self.request_id,
                    )

                    for extra in extras:
                        # Re-point all children that reference this extra asset_number
                        # Location.asset_number_id
                        session.query(Location).filter(
                            Location.asset_number_id == extra.id
                        ).update(
                            {"asset_number_id": primary.id},
                            synchronize_session="fetch",
                        )

                        # Subassembly.asset_number_id
                        session.query(Subassembly).filter(
                            Subassembly.asset_number_id == extra.id
                        ).update(
                            {"asset_number_id": primary.id},
                            synchronize_session="fetch",
                        )

                        # ComponentAssembly.asset_number_id
                        session.query(ComponentAssembly).filter(
                            ComponentAssembly.asset_number_id == extra.id
                        ).update(
                            {"asset_number_id": primary.id},
                            synchronize_session="fetch",
                        )

                        # AssemblyView.asset_number_id
                        session.query(AssemblyView).filter(
                            AssemblyView.asset_number_id == extra.id
                        ).update(
                            {"asset_number_id": primary.id},
                            synchronize_session="fetch",
                        )

                        # Finally delete the extra AssetNumber row itself
                        session.delete(extra)
                        duplicates_removed += 1

                if duplicates_removed > 0:
                    info_id(
                        f"Removed {duplicates_removed} AssetNumber duplicates "
                        f"via FK-aware merge",
                        self.request_id,
                    )
                    self.stats["duplicates_removed"] += duplicates_removed

        except Exception as e:
            error_id(
                f"Error in FK-aware AssetNumber dedupe: {str(e)}",
                self.request_id,
            )
            raise

    def _dedupe_subassemblies(self, session):
        """
        Merge duplicate Subassembly rows safely.

        You chose **B**:
            - Subassembly.name is NOT globally unique.
            - The same name can exist on different assets.

        So the natural key is:
            (name, asset_number_id, location_id)

        Strategy:
        - For each (name, asset_number_id, location_id) that has >1 rows:
            - Keep the lowest id row as canonical.
            - Re-point ComponentAssembly.subassembly_id from the extras
              to the canonical id.
            - Delete the extra Subassembly rows.

        IMPORTANT:
        - We NEVER set subassembly_id to NULL.
        - We ONLY change it from one valid id to another valid id.
        """
        label = "Subassembly"
        info_id(
            f"FK-aware dedupe for {label} based on (name, asset_number_id, location_id)",
            self.request_id,
        )

        try:
            with session.no_autoflush:
                duplicates = (
                    session.query(
                        Subassembly.name,
                        Subassembly.asset_number_id,
                        Subassembly.location_id,
                        func.count(Subassembly.id).label("count"),
                    )
                    .group_by(
                        Subassembly.name,
                        Subassembly.asset_number_id,
                        Subassembly.location_id,
                    )
                    .having(func.count(Subassembly.id) > 1)
                    .all()
                )

                if not duplicates:
                    return

                duplicates_removed = 0

                for name_value, asset_number_id, location_id, _ in duplicates:
                    rows = (
                        session.query(Subassembly)
                        .filter(
                            Subassembly.name == name_value,
                            Subassembly.asset_number_id == asset_number_id,
                            Subassembly.location_id == location_id,
                        )
                        .order_by(Subassembly.id.asc())
                        .all()
                    )

                    if len(rows) < 2:
                        continue

                    primary = rows[0]
                    extras = rows[1:]

                    debug_id(
                        f"[Subassembly dedupe] name={name_value}, "
                        f"asset_number_id={asset_number_id}, location_id={location_id}, "
                        f"keeping id={primary.id}, merging {len(extras)} duplicates",
                        self.request_id,
                    )

                    for extra in extras:
                        # Re-point ComponentAssembly.subassembly_id
                        session.query(ComponentAssembly).filter(
                            ComponentAssembly.subassembly_id == extra.id
                        ).update(
                            {"subassembly_id": primary.id},
                            synchronize_session="fetch",
                        )

                        # Delete the extra subassembly
                        session.delete(extra)
                        duplicates_removed += 1

                if duplicates_removed > 0:
                    info_id(
                        f"Removed {duplicates_removed} Subassembly duplicates "
                        f"via FK-aware merge",
                        self.request_id,
                    )
                    self.stats["duplicates_removed"] += duplicates_removed

        except Exception as e:
            error_id(
                f"Error in FK-aware Subassembly dedupe: {str(e)}",
                self.request_id,
            )
            raise


    def delete_duplicates_enhanced(self, session, model, attribute, label):
        """
        Enhanced duplicate removal with detailed logging.

        Special cases:
        - AssetNumber: use FK-aware merge based on 'number'.
        - Subassembly: use FK-aware merge based on (name, asset_number_id, location_id).

        All other tables fall back to the generic:
        - group by the attribute
        - keep the first row
        - delete the extra rows
        """
        # FK-aware special cases first
        if model is AssetNumber:
            self._dedupe_asset_numbers(session)
            return

        if model is Subassembly:
            self._dedupe_subassemblies(session)
            return

        # Generic duplicate removal for the rest
        try:
            info_id(
                f"Removing duplicates from {label} based on '{attribute}'",
                self.request_id,
            )

            with session.no_autoflush:
                duplicates = (
                    session.query(
                        getattr(model, attribute),
                        func.count().label("count"),
                    )
                    .group_by(getattr(model, attribute))
                    .having(func.count() > 1)
                    .all()
                )

                duplicates_removed = 0

                for attr_value, _ in duplicates:
                    records = (
                        session.query(model)
                        .filter(getattr(model, attribute) == attr_value)
                        .order_by(model.id.asc())
                        .all()
                    )

                    # Keep the first record, delete the rest
                    for record in records[1:]:
                        session.delete(record)
                        duplicates_removed += 1

            if duplicates_removed > 0:
                info_id(
                    f"Removed {duplicates_removed} duplicates from {label}",
                    self.request_id,
                )
                self.stats["duplicates_removed"] += duplicates_removed

        except Exception as e:
            error_id(
                f"Error removing duplicates from {label}: {str(e)}",
                self.request_id,
            )
            raise

    # ------------------------------------------------------------------
    #  Per-table processing with ID mapping
    # ------------------------------------------------------------------
    def process_single_table(self, session, df, model_class, sheet_name):
        """
        Process a single table with ID-based relationship mapping.

        ✔ CRITICAL CHANGES:
        1. Extract Excel ID from row["id"]
        2. Create/retrieve database object (with DB-assigned PK)
        3. Resolve foreign keys using self.resolve_foreign_key()
        4. Store mapping: excel_id_map[sheet_name][excel_id] = db_obj
        """
        label = model_class.__name__
        info_id(f"Processing {label} table with ID mapping", self.request_id)
        info_id(f"Processing {label}...")

        try:
            processed_count = 0

            for index, row in df.iterrows():
                try:
                    # ✔ Extract Excel ID (this is NOT the database PK)
                    excel_id = None
                    if "id" in row and row["id"] is not None:
                        try:
                            excel_id = int(row["id"])
                        except (ValueError, TypeError):
                            warning_id(
                                f"Invalid Excel ID in {label} row {index}: {row['id']}",
                                self.request_id,
                            )

                    # ----------------------
                    # CAMPUS
                    # ----------------------
                    if model_class is Campus:
                        name = (
                            str(row["name"]).strip()
                            if ("name" in row and row["name"] is not None)
                            else ""
                        )
                        if not name:
                            continue

                        # Find or create by name (natural key)
                        campus = (
                            session.query(Campus).filter_by(name=name).first()
                        )
                        if not campus:
                            campus = Campus(name=name)

                        campus.description = row["description"] if "description" in row else None
                        campus.city = row["city"] if "city" in row else None
                        campus.state = row["state"] if "state" in row else None
                        campus.country = row["country"] if "country" in row else None

                        session.add(campus)
                        session.flush()  # ✔ Get database-assigned ID

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["campus"][excel_id] = campus

                        processed_count += 1

                    # ----------------------
                    # BUILDING
                    # ----------------------
                    elif model_class is Building:
                        name = (
                            str(row["name"]).strip()
                            if ("name" in row and row["name"] is not None)
                            else ""
                        )
                        if not name:
                            continue

                        # ✔ Resolve campus_id using Excel ID → DB ID mapping
                        campus_id = self.resolve_foreign_key("campus", row.get("campus_id"))

                        building = (
                            session.query(Building)
                            .filter_by(name=name)
                            .first()
                        )
                        if not building:
                            building = Building(name=name)

                        building.description = (
                            row["description"] if "description" in row else None
                        )
                        building.address = row["address"] if "address" in row else None
                        building.campus_id = campus_id

                        session.add(building)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["building"][excel_id] = building

                        processed_count += 1

                    # ----------------------
                    # SITE LOCATION
                    # ----------------------
                    elif model_class is SiteLocation:
                        title = (
                            str(row["title"]).strip()
                            if ("title" in row and row["title"] is not None)
                            else ""
                        )
                        if not title:
                            continue

                        # ✔ Resolve building_id using Excel ID → DB ID mapping
                        building_id = self.resolve_foreign_key("building", row.get("building_id"))

                        site_location = (
                            session.query(SiteLocation)
                            .filter_by(title=title)
                            .first()
                        )
                        if not site_location:
                            site_location = SiteLocation(title=title)

                        site_location.room_number = (
                            str(row["room_number"]).strip()
                            if ("room_number" in row and row["room_number"] is not None)
                            else ""
                        )
                        site_location.site_area = (
                            str(row["site_area"]).strip()
                            if ("site_area" in row and row["site_area"] is not None)
                            else ""
                        )
                        if hasattr(site_location, "building_id"):
                            site_location.building_id = building_id

                        session.add(site_location)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["site_location"][excel_id] = site_location

                        processed_count += 1

                    # ----------------------
                    # AREA
                    # ----------------------
                    elif model_class is Area:
                        name = (
                            str(row["name"]).strip()
                            if ("name" in row and row["name"] is not None)
                            else ""
                        )
                        if not name:
                            continue

                        area = (
                            session.query(Area).filter_by(name=name).first()
                        )
                        if not area:
                            area = Area(name=name)

                        area.description = (
                            row["description"] if "description" in row else None
                        )

                        session.add(area)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["area"][excel_id] = area

                        processed_count += 1

                    # ----------------------
                    # EQUIPMENT GROUP
                    # ----------------------
                    elif model_class is EquipmentGroup:
                        name = (
                            str(row["name"]).strip()
                            if ("name" in row and row["name"] is not None)
                            else ""
                        )
                        if not name:
                            continue

                        # ✔ Resolve area_id using Excel ID → DB ID mapping
                        area_id = self.resolve_foreign_key("area", row.get("area_id"))

                        group = (
                            session.query(EquipmentGroup)
                            .filter_by(name=name)
                            .first()
                        )
                        if not group:
                            group = EquipmentGroup(name=name)

                        group.area_id = area_id
                        group.description = (
                            row["description"] if "description" in row else None
                        )

                        session.add(group)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["equipment_group"][excel_id] = group

                        processed_count += 1

                    # ----------------------
                    # MODEL
                    # ----------------------
                    elif model_class is Model:
                        name = (
                            str(row["name"]).strip()
                            if ("name" in row and row["name"] is not None)
                            else ""
                        )
                        if not name:
                            continue

                        # ✔ Resolve equipment_group_id using Excel ID → DB ID mapping
                        equipment_group_id = self.resolve_foreign_key(
                            "equipment_group", row.get("equipment_group_id")
                        )

                        model = (
                            session.query(Model).filter_by(name=name).first()
                        )
                        if not model:
                            model = Model(name=name)

                        model.description = (
                            row["description"] if "description" in row else None
                        )
                        model.equipment_group_id = equipment_group_id

                        session.add(model)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["model"][excel_id] = model

                        processed_count += 1

                    # ----------------------
                    # ASSET NUMBER
                    # ----------------------
                    elif model_class is AssetNumber:
                        number = (
                            str(row["number"]).strip()
                            if ("number" in row and row["number"] is not None)
                            else ""
                        )
                        if not number:
                            continue

                        # ✔ Resolve model_id using Excel ID → DB ID mapping
                        model_id = self.resolve_foreign_key("model", row.get("model_id"))

                        asset = (
                            session.query(AssetNumber)
                            .filter_by(number=number)
                            .first()
                        )
                        if not asset:
                            asset = AssetNumber(number=number)

                        asset.model_id = model_id
                        asset.description = (
                            row["description"] if "description" in row else None
                        )

                        session.add(asset)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["asset_number"][excel_id] = asset

                        processed_count += 1

                    # ----------------------
                    # LOCATION
                    # ----------------------
                    elif model_class is Location:
                        name = (
                            str(row["name"]).strip()
                            if ("name" in row and row["name"] is not None)
                            else ""
                        )
                        if not name:
                            continue

                        # ✔ Resolve foreign keys
                        model_id = self.resolve_foreign_key("model", row.get("model_id"))
                        asset_number_id = self.resolve_foreign_key(
                            "asset_number", row.get("asset_number_id")
                        )

                        loc = (
                            session.query(Location)
                            .filter_by(name=name)
                            .first()
                        )
                        if not loc:
                            loc = Location(name=name)

                        loc.model_id = model_id
                        if hasattr(loc, "asset_number_id"):
                            loc.asset_number_id = asset_number_id
                        if "description" in row:
                            loc.description = row["description"]

                        session.add(loc)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["location"][excel_id] = loc

                        processed_count += 1

                    # ----------------------
                    # SUBASSEMBLY
                    # ----------------------
                    elif model_class is Subassembly:
                        name = (
                            str(row["name"]).strip()
                            if ("name" in row and row["name"] is not None)
                            else ""
                        )
                        if not name:
                            continue

                        # ✔ Resolve foreign keys
                        location_id = self.resolve_foreign_key("location", row.get("location_id"))
                        asset_number_id = self.resolve_foreign_key(
                            "asset_number", row.get("asset_number_id")
                        )

                        sa = (
                            session.query(Subassembly)
                            .filter_by(name=name)
                            .first()
                        )
                        if not sa:
                            sa = Subassembly(name=name)

                        if hasattr(sa, "location_id"):
                            sa.location_id = location_id
                        if hasattr(sa, "asset_number_id"):
                            sa.asset_number_id = asset_number_id
                        sa.description = (
                            row["description"] if "description" in row else None
                        )

                        session.add(sa)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["subassembly"][excel_id] = sa

                        processed_count += 1

                    # ----------------------
                    # COMPONENT ASSEMBLY
                    # ----------------------
                    elif model_class is ComponentAssembly:
                        name = (
                            str(row["name"]).strip()
                            if ("name" in row and row["name"] is not None)
                            else ""
                        )
                        if not name:
                            continue

                        # ✔ Resolve foreign keys
                        subassembly_id = self.resolve_foreign_key(
                            "subassembly", row.get("subassembly_id")
                        )
                        asset_number_id = self.resolve_foreign_key(
                            "asset_number", row.get("asset_number_id")
                        )

                        ca = (
                            session.query(ComponentAssembly)
                            .filter_by(name=name)
                            .first()
                        )
                        if not ca:
                            ca = ComponentAssembly(name=name)

                        ca.description = (
                            row["description"] if "description" in row else None
                        )
                        if hasattr(ca, "subassembly_id"):
                            ca.subassembly_id = subassembly_id
                        if hasattr(ca, "asset_number_id"):
                            ca.asset_number_id = asset_number_id

                        session.add(ca)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["component_assembly"][excel_id] = ca

                        processed_count += 1

                    # ----------------------
                    # ASSEMBLY VIEW
                    # ----------------------
                    elif model_class is AssemblyView:
                        name = (
                            str(row["name"]).strip()
                            if ("name" in row and row["name"] is not None)
                            else ""
                        )
                        if not name:
                            continue

                        # ✔ Resolve foreign keys
                        component_assembly_id = self.resolve_foreign_key(
                            "component_assembly", row.get("component_assembly_id")
                        )
                        asset_number_id = self.resolve_foreign_key(
                            "asset_number", row.get("asset_number_id")
                        )

                        av = (
                            session.query(AssemblyView)
                            .filter_by(name=name)
                            .first()
                        )
                        if not av:
                            av = AssemblyView(name=name)

                        av.description = (
                            row["description"] if "description" in row else None
                        )
                        if hasattr(av, "component_assembly_id"):
                            av.component_assembly_id = component_assembly_id
                        if hasattr(av, "asset_number_id"):
                            av.asset_number_id = asset_number_id

                        session.add(av)
                        session.flush()

                        # ✔ Store mapping
                        if excel_id is not None:
                            self.excel_id_map["assembly_view"][excel_id] = av

                        processed_count += 1

                    # ------------- progress logging -------------
                    if processed_count and processed_count % 100 == 0:
                        debug_id(
                            f"Processed {processed_count} {label} records",
                            self.request_id,
                        )

                except Exception as e:
                    error_id(
                        f"Error processing {label} row {index}: {str(e)}",
                        self.request_id,
                    )
                    self.stats["errors_encountered"] += 1
                    try:
                        session.rollback()
                    except Exception:
                        pass
                    continue

            # Update statistics using stat_key_map
            stat_key = self.stat_key_map.get(sheet_name)
            if stat_key in self.stats:
                self.stats[stat_key] = processed_count

            info_id(
                f"Processed {processed_count} {label} records with ID mapping",
                self.request_id
            )
            info_id(f"Processed {processed_count} records")

        except Exception as e:
            error_id(
                f"Error processing {label} table: {str(e)}", self.request_id
            )
            raise

    # ------------------------------------------------------------------
    #  Revision snapshots
    # ------------------------------------------------------------------
    def create_revision_snapshots(self, main_session):
        """Create revision control snapshots with enhanced error handling."""
        try:
            info_id("Creating revision control snapshots", self.request_id)
            info_id("Creating revision snapshots...")

            with log_timed_operation(
                    "create_revision_snapshots", self.request_id
            ):
                rev_session = RevisionControlSession()

                try:
                    new_version = VersionInfo(
                        version_number=1,
                        description="Equipment relationships data import with ID-based mapping",
                    )
                    rev_session.add(new_version)
                    rev_session.commit()

                    snapshots_created = 0

                    snapshot_mapping = [
                        (Area, AreaSnapshot, "areas"),
                        (
                            EquipmentGroup,
                            EquipmentGroupSnapshot,
                            "equipment groups",
                        ),
                        (Model, ModelSnapshot, "models"),
                        (AssetNumber, AssetNumberSnapshot, "asset numbers"),
                        (Location, LocationSnapshot, "locations"),
                    ]

                    for entity_class, snapshot_class, entity_name in snapshot_mapping:
                        try:
                            entities = main_session.query(entity_class).all()
                            for entity in entities:
                                create_snapshot(
                                    entity, rev_session, snapshot_class
                                )
                                snapshots_created += 1

                            info_id(
                                f"Created {len(entities)} {entity_name} snapshots",
                                self.request_id,
                            )

                        except Exception as e:
                            warning_id(
                                f"Error creating {entity_name} snapshots: {str(e)}",
                                self.request_id,
                            )

                    # Optional SiteLocation snapshots if class exists
                    try:
                        from modules.emtacdb.emtac_revision_control_db import (
                            SiteLocationSnapshot,
                        )

                        site_locations = (
                            main_session.query(SiteLocation).all()
                        )
                        for site_location in site_locations:
                            create_snapshot(
                                site_location,
                                rev_session,
                                SiteLocationSnapshot,
                            )
                            snapshots_created += 1

                        info_id(
                            f"Created {len(site_locations)} site location snapshots",
                            self.request_id,
                        )

                    except ImportError:
                        warning_id(
                            "SiteLocationSnapshot class not found - skipping site location snapshots",
                            self.request_id,
                        )
                    except Exception as e:
                        warning_id(
                            f"Error creating site location snapshots: {str(e)}",
                            self.request_id,
                        )

                    rev_session.commit()
                    self.stats["snapshots_created"] = snapshots_created

                    info_id(
                        f"Created {snapshots_created} total snapshots",
                        self.request_id,
                    )
                    info_id(f"Created {snapshots_created} snapshots")

                except Exception as e:
                    rev_session.rollback()
                    error_id(
                        f"Error in revision snapshot creation: {str(e)}",
                        self.request_id,
                    )
                    raise
                finally:
                    rev_session.close()

        except Exception as e:
            error_id(
                f"Error creating revision snapshots: {str(e)}", self.request_id
            )
            warning_id(f"Snapshot creation failed: {str(e)}")

    # ------------------------------------------------------------------
    #  Summary
    # ------------------------------------------------------------------
    def display_processing_summary(self):
        """Display comprehensive processing summary."""
        info_id("Processing Summary")
        info_id("=" * 40)

        for key, value in self.stats.items():
            if value > 0:
                formatted_key = key.replace("_", " ").title()
                info_id(f"{formatted_key}: {value}")

        if self.stats["errors_encountered"] > 0:
            warning_id(
                f"Errors Encountered: {self.stats['errors_encountered']}"
            )

        info_id(f"Processing summary: {self.stats}", self.request_id)

    # ------------------------------------------------------------------
    #  Main loader
    # ------------------------------------------------------------------
    def load_equipment_relationships(self, file_path=None):
        """Main method to load equipment relationships data with ID-based mapping."""
        try:
            info_id("Equipment Relationships Data Import (ID-Based Mapping)")
            info_id("=" * 60)

            # Determine file path
            if not file_path:
                file_path = os.path.join(
                    DB_LOADSHEET, "Position_Loadsheet_Template.xlsx"
                )

            # Validate Excel file
            is_valid, message = self.validate_excel_file(file_path)
            if not is_valid:
                raise ValueError(f"Invalid Excel file: {message}")

            info_id(f"Loading from: {os.path.basename(file_path)}")

            # Get database session
            with self.db_config.main_session() as session:
                # Ensure tables exist
                self.create_database_tables(session)

                # Check existing data
                if not self.check_existing_data(session):
                    return False

                # Create backup
                self.create_database_backup(session)

                # Process each table in correct FK dependency order
                info_id("Processing tables with ID-based relationship mapping...")

                for sheet_name, model_class, required_columns in self.table_order:
                    try:
                        with log_timed_operation(
                                f"load_{sheet_name}_sheet", self.request_id
                        ):
                            df_raw = pd.read_excel(
                                file_path, sheet_name=sheet_name
                            )
                            df_cleaned = self.clean_dataframe(
                                df_raw, required_columns, sheet_name
                            )

                        self.process_single_table(
                            session, df_cleaned, model_class, sheet_name
                        )

                    except Exception as e:
                        error_id(
                            f"Error processing {sheet_name}: {str(e)}",
                            self.request_id,
                        )
                        self.stats["errors_encountered"] += 1
                        error_id(f"Error processing {sheet_name}: {str(e)}")
                        try:
                            session.rollback()
                        except Exception:
                            pass
                        continue

                # Remove duplicates (based on natural keys)
                # ✔ CRITICAL: Process in REVERSE dependency order to avoid FK violations
                info_id("Removing duplicates based on natural keys (not Excel IDs)...")
                info_id("Processing in reverse dependency order to handle foreign keys...")

                duplicate_mappings = [
                    # Children first (bottom of dependency tree)
                    (AssemblyView, "name", "AssemblyView"),
                    (ComponentAssembly, "name", "ComponentAssembly"),
                    (Subassembly, "name", "Subassembly"),
                    (Location, "name", "Location"),
                    # Then parents
                    (AssetNumber, "number", "AssetNumber"),
                    (Model, "name", "Model"),
                    (EquipmentGroup, "name", "EquipmentGroup"),
                    (Area, "name", "Area"),
                    (SiteLocation, "title", "SiteLocation"),
                    (Building, "name", "Building"),
                    (Campus, "name", "Campus"),
                ]

                for model_class, attribute, label in duplicate_mappings:
                    try:
                        self.delete_duplicates_enhanced(
                            session, model_class, attribute, label
                        )
                    except Exception as e:
                        # Log but continue - some tables might not have duplicates
                        warning_id(
                            f"Could not clean duplicates from {label}: {str(e)}",
                            self.request_id,
                        )
                        # Don't increment error count for expected FK issues
                        continue

                # Commit all changes
                session.commit()
                info_id(
                    "All database changes committed successfully",
                    self.request_id,
                )
                info_id("All changes committed to database")

                # Create revision snapshots (for subset of tables)
                self.create_revision_snapshots(session)

            # Display summary
            self.display_processing_summary()

            info_id("Equipment Relationships Import Completed Successfully!")
            info_id(
                "Equipment relationships import completed successfully",
                self.request_id,
            )

            return True

        except Exception as e:
            error_id(
                f"Equipment relationships import failed: {str(e)}",
                self.request_id,
                exc_info=True,
            )
            error_id(f"Import failed: {str(e)}")
            return False


def main():
    """
    Main function to load equipment relationships data with ID-based mapping.
    Uses the new PostgreSQL framework with ID resolution architecture.
    """
    info_id("Starting Equipment Relationships Data Import (ID-Based)")
    info_id("=" * 60)

    loader = None
    try:
        loader = PostgreSQLEquipmentRelationshipsLoader()
        success = loader.load_equipment_relationships()

        if success:
            info_id("Equipment Relationships Import Completed Successfully!")
            info_id("=" * 60)
        else:
            warning_id("Equipment Relationships Import Completed with Issues")
            info_id("=" * 60)

    except KeyboardInterrupt:
        warning_id("Import interrupted by user")
        if loader:
            error_id("Import interrupted by user", loader.request_id)
    except Exception as e:
        error_id(f"Import failed: {str(e)}")
        if loader:
            error_id(
                f"Import failed: {str(e)}",
                loader.request_id,
                exc_info=True,
            )
    finally:
        try:
            close_initializer_logger()
        except Exception:
            pass


if __name__ == "__main__":
    main()